services:
  express_container:
    build:
      context: .
      dockerfile: DockerFile.dev
    ports:
      - "3001:3000"
    links:
      - mongodb_container
    environment:
      - SECRET_KEY=your-secret-key
      - MONGODB_URI=mongodb://your-db-user:your-db-password@mongodb_container:27017/miapp?authSource=admin
    volumes:
      - ./app:/home/app/app
  mongodb_container:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your-db-user
      - MONGO_INITDB_ROOT_PASSWORD=your-db-password
    volumes:
      - rms_mongo_volume:/data/db
volumes:
  rms_mongo_volume: