services:
  express_container:
    build: .
    ports:
      - "3000:3001"
    links:
      - mongodb_container
    environment:
    - SECRET_KEY=asdfsdfvhgh1156165165dgdg616156
  mongodb_container:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - rms_mongo_volume:/data/db
volumes:
  rms_mongo_volume: