services:
  - type: web
    name: reservationManagementSystem
    env: docker
    repo: https://github.com/AfsBackendDev/reservationManagementSystem
    plan: free
    dockerCommand: "docker-compose up"