name: publish
on:
  workflow_dispatch:
      inputs:
        just-an-input:
          description: "just an input"
          required: false
          default: "default-value"
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: sshpass install
        run: |
          sudo apt-get update
          sudo apt-get install sshpass
      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PEM_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MY_PEM_KEY }}
      - name: Deploy to vm of azure
        env:
            SSH_PASS: ${{ secrets.MY_PEM_KEY }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sudo ssh -t -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
            cd reservationManagementSystem/
            git pull origin main
            sudo docker compose up -d --build
          EOF