name: publish
on:
  push:
    branches:
      - main
jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: sshpass install
        run: |
          sudo apt-get update
          sudo apt-get install sshpass
      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
  deploy:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Deploy to vm of azure
        env:
            SSH_PASS: ${{ secrets.MY_PEM_KEY }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sudo ssh -t -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
            cd appRepo/RESTful-API/
            git pull origin main
            sudo docker compose down --rmi all
            sudo docker compose up -d --build
          EOF